# channel_alias: https://@PROXY_USER@:@PROXY_PASS@@artifactory.dhl.com/artifactory/api/conda/conda

# channels:
#   - https://@PROXY_USER@:@PROXY_PASS@@artifactory.dhl.com/artifactory/api/conda/conda

# default_channels:
#   - https://@PROXY_USER@:@PROXY_PASS@@artifactory.dhl.com/artifactory/api/conda/conda

# ssl_verify: false

# For the environment.yml to reliably use the conda-forge packages,
# need to set this option.  See https://github.com/conda-forge/sagelib-feedstock/issues/87
channel_priority: strict
channels:
  - conda-forge
  - defaults
